#Custom Help Developed by Rexy.
#Version: BETA 1.0
#1.8 tested, if you test another version let me know if it works or doesnt!
#Fun fact i ate 4 grilled cheese while coding this.

Help:
  - '&7&m----------(&c&l Help &7&m)----------'
  - ''
  - '&c&lCommand&8: &eEdit in config.yml'
  - '&c&lCommand&8: &eEdit in config.yml'
  - '&c&lCommand&8: &eEdit in config.yml'
  - '&c&lCommand&8: &eEdit in config.yml'
  - '&c&lCommand&8: &eEdit in config.yml'
  - '&c&lCommand&8: &eEdit in config.yml'
  - '&c&lCommand&8: &eEdit in config.yml'
  - '&a&lPlease leave a review on the spigot page!'
  - '&b&lAlso join my coding discord https://discord.gg/PRNyMWf'
  - ''
  - '&7&m----------------------------'